global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fix-gateway'
    static_configs:
      - targets: ['fix-gateway:8081']
    scrape_interval: 5s
    metrics_path: /metrics
    
  - job_name: 'redis'
    static_configs:
      - targets: ['message-broker:6379']
    scrape_interval: 10s
